### ISSUE TITLE
ADB和WIFI做一个开关

### ISSUE THREAD

**Issue by xiexuanwen** [pass0a/poseidon#26]
**问题描述**
简短的描述你遇到的问题

**如何重现**
重现步骤:

**期望结果**
简短的描述你期望系统如何表现

**截图**
如果可以，请添加截图说明你的问题

**桌面环境 (请完善如下信息):**
 - Version [e.g. 系统的版本]

**待测设备 (请完善如下信息):**
 - Device: [e.g. 小米6]
 - OS: [e.g. android 4.4]

**附加说明**
添加其他任何你认为需要明确的信息

**Comment by hzp2019** [comment]
已解决
