### ISSUE TITLE
安装好软件，第一次编辑的用例，一但运行后用例会在显示消失。重新关闭打开软件才能看见用例

### ISSUE THREAD

**Issue by xiexuanwen** [pass0a/poseidon#33]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. windows]

**Smartphone (please complete the following information):**
 - Device: [e.g. xiaomi 6s]
 - OS: [e.g. android 4.4]

**Additional context**

**Comment by hzp2019** [comment]
已解决
