### ISSUE TITLE
继续运行用例，没有重新下载测试用例

### ISSUE THREAD

**Issue by xiexuanwen** [pass0a/poseidon#34]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. windows]

**Smartphone (please complete the following information):**
 - Device: [e.g. xiaomi 6s]
 - OS: [e.g. android 4.4]

**Additional context**

**Comment by hzp2019** [comment]
已解决
