### ISSUE TITLE
添加摄像头设置功能

### ISSUE THREAD

**Issue by xiexuanwen** [pass0a/poseidon#35]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by losper** [comment]
浏览器摄像头需要通过命令行参数的方式打开，请参考下面链接
https://peter.sh/experiments/chromium-command-line-switches/

**Comment by xiexuanwen** [comment]
该功能已经添加
