### ISSUE TITLE
截图管理中的【同步车机】同步失败

### ISSUE THREAD

**Issue by xiexuanwen** [pass0a/poseidon#48]
前提条件：车机已经push子程序，IP设置对了，车机也打开了wifi
操作步骤：点击截图管理-同步车机
测试结果：显示“同步失败”
期望结果：同步成功，并把车机当前图片同步过来
发现版本：V3.2.1

**Comment by hzp2019** [comment]
已解决

**Comment by xiexuanwen** [comment]
目前先关闭，但也有时而车机ping不通电脑的问题，有待持续跟踪留意
