### ISSUE TITLE
有时候打开poseidon的时候，显示不全

### ISSUE THREAD

**Issue by xiexuanwen** [pass0a/poseidon#50]
前提条件：无
操作步骤：双击打开桌面的poseidon图标
期望结果：所有的图标能正常加载显示
实际结果：有时候不能把图标再能正常显示

**Comment by losper** [comment]
已解决。
根据HTTP协议，增加HTTP头connect:close返回给浏览器。
原本的res.js实现有问题，在关掉http连接时，没有发送connect:close给浏览器以通知浏览器连接不可用。

**Comment by xiexuanwen** [comment]
V3.2.2版本暂时没有发现此问题
