### ISSUE TITLE
偶尔用例不显示

### ISSUE THREAD

**Issue by xiexuanwen** [pass0a/poseidon#57]
前提条件：已经在System模块中，添加了两条测试用例
操作步骤：在【多项管理】-【步骤管理】/【选项管理】中，添加步骤；添加步骤后返回【编辑用例】
实际结果：原有的测试用例已经不见，需要从新关闭poseidon，再打开poseidon方能显示
预期结果：原有的测试用例保持显示
测试版本：3.2.2
发生频率：偶发

**Comment by hzp2019** [comment]
已解决

**Comment by xiexuanwen** [comment]
已解决
