### ISSUE TITLE
组合步骤的【修改】不能点击

### ISSUE THREAD

**Issue by xiexuanwen** [pass0a/poseidon#58]
前提条件：进入【多项管理】-【步骤管理】-【组合步骤】，有一条组合用例
操作步骤：点击左边的【修改】图标
实际结果：没有反应，但【删除】图标可以使用
预期结果：能修改用例的名字
测试版本：3.2.2
发生频率：always

**Comment by hzp2019** [comment]
3.2.2版本未做此功能, 现已完成

**Comment by xiexuanwen** [comment]
已完成
