### ISSUE TITLE
组合用例弹出【无法选择本身】

### ISSUE THREAD

**Issue by xiexuanwen** [pass0a/poseidon#59]
前提条件：只有一个组合用例
操作步骤：在【编辑用例】中新建一条测试用例，选择【组合用例】时，
实际结果：不可选择，提示【无法选择本身】
预期结果：可以选择组合用例
测试版本：3.2.2
发生频率：偶发

**Comment by hzp2019** [comment]
逻辑问题, 已解决

**Comment by xiexuanwen** [comment]
已修复
