### ISSUE TITLE
机器还未开机时，选用ADB+wifi的配置方式不能进行用例测试

### ISSUE THREAD

**Issue by xiexuanwen** [pass0a/poseidon#73]
前提条件：机器未开机，系统配置选择【adb+wifi】的方式
操作步骤：编辑测试用例，第一步是acc on，运行测试用例
实际结果：运行失败，提示ADB错误
预期结果：可以运行测试用例
测试版本：3.2.4
发生频率：一直

**Comment by hzp2019** [comment]
已完成, 开始测试前不检测ADB

**Comment by xiexuanwen** [comment]
已完成
