### ISSUE TITLE
从其他界面回到编辑用例界面时，需要返回到当时出去的界面

### ISSUE THREAD

**Issue by xiexuanwen** [pass0a/poseidon#85]
前提条件：在用例编辑界面-radio标签做用例编辑
操作步骤：进入步骤管理界面添加步骤，返回用例编辑界面
实际结果：返回到的是system标签
预期结果：返回到radio标签
测试版本：3.2.5
发生频率：一直

**Comment by hzp2019** [comment]
已完成

**Comment by xiexuanwen** [comment]
此问题已修复
