### ISSUE TITLE
摄像头拍摄，保存图片时显示错误

### ISSUE THREAD

**Issue by xiexuanwen** [pass0a/poseidon#94]
前提条件：在步骤管理-摄像功能
操作步骤：拍摄图片后，没有选择绑定哪一步骤时，直接点保存
实际结果：提示【绑定成功】
预期结果：提示【请保存步骤】
测试版本：3.2.6
发生频率：aways

**Comment by hzp2019** [comment]
已解决,待验证

**Comment by xiexuanwen** [comment]
V3.2.7已解决
